### PR TITLE
Bump version to 0.2.3

### PR DESCRIPTION
**Pull request by lucaswerkmeister**

### CODE REVIEW

**Comment by lucaswerkmeister** [comment]
```sh
git show @^ | sed 's/0.2.2/0.2.3/g; s/0.2.1/0.2.2/g;' | git apply
```
;)

It looks like there’s a publish-on-release workflow in this repo, so after this I should be able to tag 0.2.3 and it would end up on npm automatically, right?

**Comment by lucaswerkmeister** [comment]
Hm, apparently there’s already an eslint-config-wikimedia@0.22.1 too (we’re on 0.21 here). Should we bump that too before the release?

**Comment by micgro42** [comment]
> Hm, apparently there’s already an eslint-config-wikimedia@0.22.1 too (we’re on 0.21 here). Should we bump that too before the release?

yeah, makes sense. But could you check first what they changed?

**Comment by lucaswerkmeister** [comment]
> vue: Enforce component-name-in-template-casing

Sounds like something we might want to change in individual projects, but not here, I think, since it’s not related to TypeScript. I’ll push a version update here and then see how it works in new-lexeme-special-page.

**Comment by lucaswerkmeister** [comment]
> > vue: Enforce component-name-in-template-casing
> 
> Sounds like something we might want to change in individual projects, but not here, I think, since it’s not related to TypeScript. I’ll push a version update here and then see how it works in new-lexeme-special-page.

Pushed to wmde/new-lexeme-special-page#76, seems to work fine (i.e. eslint complains about the member delimiter style, but not about anything else).

**Pull request merged**
